version: '3'
services:
  hellodockertools:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '80'
networks:
  default:
    external:
      name: <span data-ttu-id="72534-101">Translator adresów sieciowych</span><span class="sxs-lookup"><span data-stu-id="72534-101">nat</span></span>